# -*- coding: utf-8 -*-
"""
Created on Mon Jun 17 20:35:49 2024

@author: Hederson
"""

[theme]
primaryColor='colar c贸digo rgb da cor aqui'
backgroundColor='colar c贸digo rgb da cor aqui'
secondaryBackgroundColor='colar c贸digo rgb da cor aqui'
textColor='colar c贸digo rgb da cor aqui'
font='sans serif'